* Take Breath
  Take Breath is a program which reminds you when it is time to take a breath
  from your computer.

* Algorithm
  When the program starts, it starts a work time counter. When the work time
  counter is greater than 45 minutes, program notifies you to take a breath and
  starts a computer idle time counter. When the computer idle time counter is
  less than 15 minutes, program notifies you that your rest is too short and you
  should rest more. Otherwise it starts a work time counter again.

* Roadmap
  - [X] Basic algorithm implementation
  - [ ] Handle idle while work
  - [ ] Split app into library and binary parts
  - [ ] CLI implementation
  - [ ] Better error handling
  - [ ] Customization features
  - [ ] Documentation
  - [-] Support for various operating systems
    - [X] Linux
    - [ ] Mac
    - [ ] Windows

* Building
   In order to compile Take Breath program you should have [[https://www.rust-lang.org/tools/install][Rust toolchain]]
   installed. If you have, just run the following shell commands:
   #+BEGIN_SRC bash
git clone https://github.com/markmelix/take-breath.git
cd take-breath
cargo build --release
   #+END_SRC
   It puts compiled ~take-breath~ file into the ./target/release directory.

   You can also get compiled take-breath program without cloning the repository
   using the following command: ~"cargo install take-breath"~. It puts compiled
   ~take-breath~ file into the ~/.cargo/bin directory.

* Usage
  *Note that for now only Linux is supported by the program*

  Just run the following command in a terminal: "~take-breath
  &~". It executes ~take-breath~ program as a background process.

* License
  Take Breath is provided under [[./LICENSE][MIT License]].

* Contribution
  Contributions are welcome.
